CREATE TABLE "test_execution_types" (
	"id"	INTEGER,
	"type_text"	TEXT NOT NULL UNIQUE,
	"is_run"	INTEGER DEFAULT 0,
	"created_at"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
)