CREATE TABLE  "functions" (
		"id" INTEGER, "name" TEXT NOT NULL UNIQUE, 
		"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, 
		"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, 
		PRIMARY KEY("id")
);
