CREATE TABLE "testers" (
	"id"	INTEGER,
	"tester_code"	TEXT NOT NULL UNIQUE,
	"company"	TEXT NOT NULL,
	"section"	TEXT NOT NULL,
	"name"	TEXT NOT NULL,
	"created_at"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);
